### ISSUE TITLE
DH doesn't get response

### ISSUE THREAD

**Issue by brianegge** [GaryMilne/Tasmota-RGBCCT-DH-for-SmartThings-Classic-with-MQTT#1]
Tasmoto 7.0 works fine via curl, but not in ST.
```
 5:33:24 PM: debug 🔂 0️⃣..Poll: Polling started..
 5:18:31 PM: debug 🔄 🛑..sync: Sync Failed...12.605 seconds
5:18:31 PM: debug 🏁 🛑........checkResponse: Fail-Timeout
 5:18:19 PM: debug 🏃 0️⃣......useTransactions: True - Command: STATE
 5:18:19 PM: debug ⇢💡 0️⃣..callTasmota: Sending command: STATE
 5:18:19 PM: debug 👍 0️⃣..isSystemIdle: True - callTasmota() - Allowed
 5:18:23 PM: debug 👎 0️⃣..isSystemIdle: False - callTasmota() - Blocked
 5:18:23 PM: debug 🔂 0️⃣..Poll: Polling started..
```

**Comment by GaryMilne** [comment]
Brian, most likely issue is that your Device Network Interface is not set correctly.  Click on the DNI button at the bottom of the screen and have a look at the log. It will either say it is already correct and do nothing or it is not correct and try to fix it.

Sometime I have found that the Smartthings hub takes a little while to recognize when an IP address is moved from one device to another, most likely the arp cache. But waiting about 15 minutes is usually enough to clear it.

**Comment by brianegge** [comment]
Pressing the DNI button fixed the issue! Thank you. Both were assigned to new IPs, not leased out on my LAN before. They were on the network for some two hours, so ST is not doing this automatically.

**Comment by GaryMilne** [comment]
The DNI gets calculated when you enter the IP address and save the settings. But you are right that sometimes it does not work the first time which is why I called this problem out in the docs. As you said clicking on the DNI manually should correct it.
