### ISSUE TITLE
Device not available in new Smartthings App

### ISSUE THREAD

**Issue by magnazan** [GaryMilne/Tasmota-RGBCCT-DH-for-SmartThings-Classic-with-MQTT#3]
I know that the DH is designed for the classic app and it works very well so thanks for that. The issue I have is that I have automations in the new app which the RGB bulbs cannot participate. To compound this routines are not available in the classic app once they have all been removed (I'm a new user so never had any in there).

My question is are you planning to switch this over to the newer app?

**Comment by GaryMilne** [comment]
Unfortunately the platform for the new Smartthings app has many limitations that prevent any type of similar device handler at present. Most notably is that Hub connected (which this is considered to be) only supports ZWave and Zigbee at present. And if that were not enough the new interface does not allow for the provisioning of custom features.

In classic I can create a button, make it look however I want and execute anything I want. In the new version this is not the case and it only supports specific capabilities.

So we are out of luck as it stands today. But they say that they will run the two platforms in tandem until such time as the new platform reaches parity with the old but personally I don't believe it.

I'm about half Samsung and half Tasmota devices. So I'm waiting for more clarity but if I have to dump one or the other it will be Samsung that I hit the eject button on.
